/**
 * PDF Service - PDF Generation, Editing, and Template System
 * Part of Galion.studio Ecosystem - Galion Initiative (40% Open Source)
 * Serverless-ready
 */

import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

class PDFService {
  constructor() {
    this.templatesDir = path.join(process.cwd(), 'downloads', 'templates');
    this.outputDir = path.join(process.cwd(), 'downloads', 'pdfs');
  }

  async initialize() {
    await fs.mkdir(this.templatesDir, { recursive: true });
    await fs.mkdir(this.outputDir, { recursive: true });
    console.log('✓ PDF Service initialized');
  }

  /**
   * Generate HTML-based PDF content with research template
   */
  generateResearchTemplate(options = {}) {
    const {
      title = 'Research Paper',
      author = 'Galion Initiative',
      abstract = '',
      sections = [],
      references = [],
      style = 'academic',
      theme = 'light'
    } = options;

    const styles = this.getTemplateStyles(style, theme);
    
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    ${styles}
  </style>
</head>
<body>
  <div class="document">
    <header class="document-header">
      <h1 class="title">${title}</h1>
      <p class="author">By ${author}</p>
      <p class="date">${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    </header>

    ${abstract ? `
    <section class="abstract">
      <h2>Abstract</h2>
      <p>${abstract}</p>
    </section>
    ` : ''}

    ${sections.map((section, idx) => `
    <section class="content-section">
      <h2>${idx + 1}. ${section.title}</h2>
      ${section.content.split('\n').map(p => `<p>${p}</p>`).join('')}
      ${section.subsections ? section.subsections.map((sub, subIdx) => `
        <h3>${idx + 1}.${subIdx + 1} ${sub.title}</h3>
        ${sub.content.split('\n').map(p => `<p>${p}</p>`).join('')}
      `).join('') : ''}
    </section>
    `).join('')}

    ${references.length > 0 ? `
    <section class="references">
      <h2>References</h2>
      <ol>
        ${references.map(ref => `<li>${ref}</li>`).join('')}
      </ol>
    </section>
    ` : ''}

    <footer class="document-footer">
      <p class="galion-branding">
        Generated by Galion Initiative • <a href="https://galion.app">galion.app</a>
      </p>
    </footer>
  </div>
</body>
</html>`;
  }

  /**
   * Get template styles based on style type and theme
   */
  getTemplateStyles(style, theme) {
    const baseStyles = `
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      
      @page {
        size: A4;
        margin: 2.5cm;
      }
      
      body {
        font-family: 'Times New Roman', Times, serif;
        font-size: 12pt;
        line-height: 1.6;
        color: ${theme === 'dark' ? '#e0e0e0' : '#1a1a1a'};
        background: ${theme === 'dark' ? '#1a1a1a' : '#ffffff'};
      }
      
      .document {
        max-width: 210mm;
        margin: 0 auto;
        padding: 40px;
      }
`;

    const academicStyles = `
      .document-header {
        text-align: center;
        margin-bottom: 40px;
        padding-bottom: 20px;
        border-bottom: 1px solid ${theme === 'dark' ? '#444' : '#ddd'};
      }
      
      .title {
        font-size: 24pt;
        font-weight: bold;
        margin-bottom: 16px;
        color: ${theme === 'dark' ? '#fff' : '#000'};
      }
      
      .author {
        font-size: 14pt;
        color: ${theme === 'dark' ? '#aaa' : '#666'};
        margin-bottom: 8px;
      }
      
      .date {
        font-size: 12pt;
        color: ${theme === 'dark' ? '#888' : '#888'};
      }
      
      .abstract {
        background: ${theme === 'dark' ? '#252525' : '#f8f8f8'};
        padding: 20px;
        margin-bottom: 30px;
        border-left: 4px solid #8b5cf6;
      }
      
      .abstract h2 {
        font-size: 14pt;
        color: #8b5cf6;
        margin-bottom: 12px;
      }
      
      .abstract p {
        font-style: italic;
      }
      
      .content-section {
        margin-bottom: 30px;
      }
      
      h2 {
        font-size: 16pt;
        color: ${theme === 'dark' ? '#e0e0e0' : '#222'};
        margin-bottom: 16px;
        padding-bottom: 8px;
        border-bottom: 2px solid #8b5cf6;
      }
      
      h3 {
        font-size: 13pt;
        color: ${theme === 'dark' ? '#c0c0c0' : '#444'};
        margin-top: 20px;
        margin-bottom: 12px;
      }
      
      p {
        text-align: justify;
        margin-bottom: 12px;
        text-indent: 2em;
      }
      
      .references {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 2px solid ${theme === 'dark' ? '#444' : '#ddd'};
      }
      
      .references ol {
        padding-left: 24px;
      }
      
      .references li {
        margin-bottom: 8px;
        font-size: 11pt;
      }
      
      .document-footer {
        margin-top: 60px;
        padding-top: 20px;
        border-top: 1px solid ${theme === 'dark' ? '#444' : '#ddd'};
        text-align: center;
      }
      
      .galion-branding {
        font-size: 10pt;
        color: ${theme === 'dark' ? '#666' : '#999'};
      }
      
      .galion-branding a {
        color: #8b5cf6;
        text-decoration: none;
      }
`;

    const businessStyles = `
      .document-header {
        background: linear-gradient(135deg, #8b5cf6, #a78bfa);
        color: white;
        padding: 40px;
        margin: -40px -40px 40px -40px;
        text-align: center;
      }
      
      .title {
        font-size: 28pt;
        font-weight: bold;
        margin-bottom: 16px;
      }
      
      .author, .date {
        color: rgba(255,255,255,0.9);
      }
      
      .abstract {
        background: ${theme === 'dark' ? '#252525' : '#f0f0ff'};
        padding: 24px;
        margin-bottom: 30px;
        border-radius: 8px;
      }
      
      h2 {
        font-size: 18pt;
        color: #8b5cf6;
        margin-bottom: 20px;
      }
      
      h3 {
        font-size: 14pt;
        color: #a78bfa;
        margin-top: 24px;
        margin-bottom: 12px;
      }
      
      p {
        margin-bottom: 16px;
      }
`;

    const techStyles = `
      body {
        font-family: 'Inter', 'Segoe UI', sans-serif;
      }
      
      .document-header {
        margin-bottom: 40px;
      }
      
      .title {
        font-size: 32pt;
        font-weight: 800;
        background: linear-gradient(135deg, #8b5cf6, #c084fc);
        -webkit-background-clip: text;
        background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 16px;
      }
      
      .author {
        font-size: 14pt;
        color: ${theme === 'dark' ? '#aaa' : '#555'};
      }
      
      .abstract {
        background: ${theme === 'dark' ? '#1e1e2a' : '#f5f3ff'};
        padding: 24px;
        border-radius: 12px;
        margin-bottom: 30px;
        border: 1px solid ${theme === 'dark' ? '#333' : '#e9e4ff'};
      }
      
      h2 {
        font-size: 20pt;
        color: #8b5cf6;
        margin-bottom: 20px;
        font-weight: 600;
      }
      
      h3 {
        font-size: 14pt;
        color: #a78bfa;
        margin-top: 24px;
        margin-bottom: 12px;
        font-weight: 600;
      }
      
      p {
        margin-bottom: 16px;
        text-indent: 0;
      }
      
      code {
        background: ${theme === 'dark' ? '#2d2d3a' : '#f0f0f0'};
        padding: 2px 6px;
        border-radius: 4px;
        font-family: 'Fira Code', monospace;
        font-size: 11pt;
      }
`;

    const styleMap = {
      academic: academicStyles,
      business: businessStyles,
      tech: techStyles
    };

    return baseStyles + (styleMap[style] || academicStyles);
  }

  /**
   * Generate a visual research template
   */
  async generateVisualTemplate(options = {}) {
    const {
      type = 'poster', // poster, infographic, slide
      title = 'Visual Research',
      subtitle = '',
      sections = [],
      images = [],
      theme = 'purple',
      outputPath
    } = options;

    const themeColors = {
      purple: { primary: '#8b5cf6', secondary: '#a78bfa', gradient: 'linear-gradient(135deg, #8b5cf6, #c084fc)' },
      blue: { primary: '#3b82f6', secondary: '#60a5fa', gradient: 'linear-gradient(135deg, #3b82f6, #60a5fa)' },
      green: { primary: '#22c55e', secondary: '#4ade80', gradient: 'linear-gradient(135deg, #22c55e, #4ade80)' },
      red: { primary: '#ef4444', secondary: '#f87171', gradient: 'linear-gradient(135deg, #ef4444, #f87171)' }
    };

    const colors = themeColors[theme] || themeColors.purple;

    const templates = {
      poster: this.generatePosterTemplate(title, subtitle, sections, colors),
      infographic: this.generateInfographicTemplate(title, subtitle, sections, colors),
      slide: this.generateSlideTemplate(title, subtitle, sections, colors)
    };

    const html = templates[type] || templates.poster;
    
    if (outputPath) {
      await fs.writeFile(outputPath, html, 'utf8');
      return { success: true, path: outputPath };
    }

    return { success: true, html };
  }

  /**
   * Generate poster template
   */
  generatePosterTemplate(title, subtitle, sections, colors) {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Inter', 'Segoe UI', sans-serif;
      background: #0a0a0f;
      color: #ffffff;
      min-height: 100vh;
    }
    .poster {
      width: 100%;
      max-width: 1200px;
      margin: 0 auto;
      padding: 60px;
    }
    .poster-header {
      text-align: center;
      margin-bottom: 60px;
    }
    .poster-title {
      font-size: 48px;
      font-weight: 800;
      background: ${colors.gradient};
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 16px;
    }
    .poster-subtitle {
      font-size: 20px;
      color: #a1a1aa;
    }
    .poster-sections {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 32px;
    }
    .poster-section {
      background: #15151f;
      border: 1px solid #27272a;
      border-radius: 16px;
      padding: 32px;
    }
    .section-title {
      font-size: 24px;
      color: ${colors.primary};
      margin-bottom: 16px;
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .section-content {
      color: #a1a1aa;
      line-height: 1.8;
    }
    .poster-footer {
      margin-top: 60px;
      text-align: center;
      padding-top: 32px;
      border-top: 1px solid #27272a;
    }
    .branding {
      color: #71717a;
      font-size: 14px;
    }
    .branding a { color: ${colors.primary}; text-decoration: none; }
  </style>
</head>
<body>
  <div class="poster">
    <header class="poster-header">
      <h1 class="poster-title">${title}</h1>
      ${subtitle ? `<p class="poster-subtitle">${subtitle}</p>` : ''}
    </header>
    
    <div class="poster-sections">
      ${sections.map((section, idx) => `
        <div class="poster-section">
          <h2 class="section-title">
            <span style="font-size: 32px;">${section.icon || '📌'}</span>
            ${section.title}
          </h2>
          <div class="section-content">${section.content}</div>
        </div>
      `).join('')}
    </div>
    
    <footer class="poster-footer">
      <p class="branding">
        Created with Galion Initiative • <a href="https://galion.app">galion.app</a>
      </p>
    </footer>
  </div>
</body>
</html>`;
  }

  /**
   * Generate infographic template
   */
  generateInfographicTemplate(title, subtitle, sections, colors) {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Inter', 'Segoe UI', sans-serif;
      background: linear-gradient(180deg, #0a0a0f 0%, #15151f 100%);
      color: #ffffff;
      min-height: 100vh;
    }
    .infographic {
      width: 100%;
      max-width: 800px;
      margin: 0 auto;
      padding: 60px 40px;
    }
    .info-header {
      text-align: center;
      margin-bottom: 60px;
      padding-bottom: 40px;
      border-bottom: 2px solid ${colors.primary};
    }
    .info-title {
      font-size: 42px;
      font-weight: 800;
      color: #ffffff;
      margin-bottom: 12px;
    }
    .info-subtitle {
      font-size: 18px;
      color: ${colors.secondary};
    }
    .timeline {
      position: relative;
      padding-left: 60px;
    }
    .timeline::before {
      content: '';
      position: absolute;
      left: 20px;
      top: 0;
      bottom: 0;
      width: 4px;
      background: ${colors.gradient};
      border-radius: 2px;
    }
    .timeline-item {
      position: relative;
      margin-bottom: 40px;
    }
    .timeline-dot {
      position: absolute;
      left: -52px;
      width: 24px;
      height: 24px;
      background: ${colors.primary};
      border-radius: 50%;
      border: 4px solid #0a0a0f;
    }
    .timeline-content {
      background: #15151f;
      border: 1px solid #27272a;
      border-radius: 12px;
      padding: 24px;
    }
    .timeline-title {
      font-size: 20px;
      color: ${colors.primary};
      margin-bottom: 8px;
    }
    .timeline-text {
      color: #a1a1aa;
      line-height: 1.7;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 20px;
      margin-top: 60px;
    }
    .stat-card {
      background: #15151f;
      border: 1px solid #27272a;
      border-radius: 12px;
      padding: 24px;
      text-align: center;
    }
    .stat-number {
      font-size: 36px;
      font-weight: 800;
      color: ${colors.primary};
    }
    .stat-label {
      color: #71717a;
      font-size: 14px;
      margin-top: 8px;
    }
    .info-footer {
      margin-top: 60px;
      text-align: center;
      color: #71717a;
      font-size: 14px;
    }
    .info-footer a { color: ${colors.primary}; text-decoration: none; }
  </style>
</head>
<body>
  <div class="infographic">
    <header class="info-header">
      <h1 class="info-title">${title}</h1>
      ${subtitle ? `<p class="info-subtitle">${subtitle}</p>` : ''}
    </header>
    
    <div class="timeline">
      ${sections.map((section, idx) => `
        <div class="timeline-item">
          <div class="timeline-dot"></div>
          <div class="timeline-content">
            <h3 class="timeline-title">${section.title}</h3>
            <p class="timeline-text">${section.content}</p>
          </div>
        </div>
      `).join('')}
    </div>
    
    <footer class="info-footer">
      <p>Generated by Galion Initiative • <a href="https://galion.app">galion.app</a></p>
    </footer>
  </div>
</body>
</html>`;
  }

  /**
   * Generate slide template
   */
  generateSlideTemplate(title, subtitle, sections, colors) {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Inter', 'Segoe UI', sans-serif;
      background: #0a0a0f;
      color: #ffffff;
    }
    .slides {
      width: 100%;
    }
    .slide {
      width: 100%;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      padding: 60px;
      border-bottom: 2px solid #27272a;
    }
    .slide.title-slide {
      background: ${colors.gradient};
    }
    .slide-title {
      font-size: 56px;
      font-weight: 800;
      text-align: center;
      margin-bottom: 24px;
    }
    .slide-subtitle {
      font-size: 24px;
      opacity: 0.9;
      text-align: center;
    }
    .content-slide {
      max-width: 1000px;
    }
    .content-title {
      font-size: 36px;
      font-weight: 700;
      color: ${colors.primary};
      margin-bottom: 40px;
      text-align: center;
    }
    .content-text {
      font-size: 20px;
      color: #a1a1aa;
      line-height: 1.8;
      text-align: center;
    }
    .slide-number {
      position: absolute;
      bottom: 20px;
      right: 40px;
      color: #71717a;
      font-size: 14px;
    }
    .final-slide {
      text-align: center;
    }
    .thanks {
      font-size: 48px;
      font-weight: 800;
      background: ${colors.gradient};
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 24px;
    }
    .contact {
      font-size: 18px;
      color: #71717a;
    }
    .contact a { color: ${colors.primary}; text-decoration: none; }
  </style>
</head>
<body>
  <div class="slides">
    <!-- Title Slide -->
    <div class="slide title-slide">
      <h1 class="slide-title">${title}</h1>
      ${subtitle ? `<p class="slide-subtitle">${subtitle}</p>` : ''}
      <span class="slide-number">1</span>
    </div>
    
    <!-- Content Slides -->
    ${sections.map((section, idx) => `
    <div class="slide">
      <div class="content-slide">
        <h2 class="content-title">${section.title}</h2>
        <p class="content-text">${section.content}</p>
      </div>
      <span class="slide-number">${idx + 2}</span>
    </div>
    `).join('')}
    
    <!-- Final Slide -->
    <div class="slide final-slide">
      <p class="thanks">Thank You</p>
      <p class="contact">
        Learn more at <a href="https://galion.app">galion.app</a>
      </p>
      <span class="slide-number">${sections.length + 2}</span>
    </div>
  </div>
</body>
</html>`;
  }

  /**
   * Create editable PDF content (for frontend editing)
   */
  createEditableContent(options = {}) {
    const { content = '', fonts = [], images = [] } = options;
    
    return {
      version: '1.0',
      createdAt: new Date().toISOString(),
      content: {
        type: 'document',
        children: [
          {
            type: 'paragraph',
            children: [{ text: content }]
          }
        ]
      },
      fonts: fonts.length > 0 ? fonts : [
        { name: 'Inter', family: 'Inter, sans-serif', weight: 400 },
        { name: 'Inter Bold', family: 'Inter, sans-serif', weight: 700 },
        { name: 'Times New Roman', family: 'Times New Roman, serif', weight: 400 }
      ],
      images,
      styles: {
        pageSize: 'A4',
        margins: { top: 72, right: 72, bottom: 72, left: 72 },
        fontSize: 12,
        lineHeight: 1.6,
        color: '#000000'
      }
    };
  }

  /**
   * List available templates
   */
  async listTemplates() {
    return {
      research: [
        { id: 'academic-paper', name: 'Academic Research Paper', style: 'academic' },
        { id: 'business-report', name: 'Business Report', style: 'business' },
        { id: 'tech-doc', name: 'Technical Documentation', style: 'tech' }
      ],
      visual: [
        { id: 'research-poster', name: 'Research Poster', type: 'poster' },
        { id: 'infographic', name: 'Infographic', type: 'infographic' },
        { id: 'presentation', name: 'Presentation Slides', type: 'slide' }
      ],
      themes: ['purple', 'blue', 'green', 'red'],
      fonts: [
        'Inter',
        'Times New Roman',
        'Arial',
        'Georgia',
        'Roboto',
        'Open Sans',
        'Playfair Display',
        'Fira Code'
      ]
    };
  }
}

export { PDFService };
